"""Initial Migration

Revision ID: ce48b6631673
Revises: 9c1aca0c0e4b
Create Date: 2020-11-01 15:40:00.904994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce48b6631673'
down_revision = '9c1aca0c0e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_content', sa.Text(), nullable=False))
    op.drop_column('blogs', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('blogs', 'blog_content')
    # ### end Alembic commands ###
